### ISSUE TITLE
Question about data prerpocessing

### ISSUE THREAD

**Issue by tedhuang96** [zhangpur/SR-LSTM#2]
Hi! I am really impressed by your work on sr-lstm and I want to ask a few questions about it to better understand your work. When I am dealing with the crowd dataset, I cropped 20 time-step window and it is usually the case that some pedestrian won't show up for all 20 time steps. How did you tackle this problem? When you used origin-shift technique to preprocess the dataset, did you shift the coordinates of all pedestrians at the last observed time step to zero? If that is the case, shouldn't that affect the spatial relationship between neighbors?

Thank you in advance and look forward to your reply!

**Comment by MazenHamdi** [comment]
up
