### ISSUE TITLE
Question about data preprocessing

### ISSUE THREAD

**Issue by alexmonti19** [zhangpur/SR-LSTM#4]
Hi! 

First of all thanks for your interesting work :)

I'm looking into your code (specifically, the data pre-processing stages) because I saw it has been cited/used in other trajectory prediction works and I'm interested too in giving it a try. While scrolling through the different pre-processing steps I found something odd when extracting the datasets sampling indexes and I don't know if it's some kind of bug or if the behaviour is instead intended. More precisely, I'm talking about the `get_data_index()` function inside `utils.py`.

https://github.com/zhangpur/SR-LSTM/blob/22de027ff1eb6183fa8c2c60940e2cbf74b46822/utils.py#L148-L162

In the first two lines inside the for loop, you're extracting all the frame IDs inside a given .txt file and you're subtracting the desired sequence length (as this task requires, 20 timesteps) from the last (greatest) ID: if I understand correctly what you're trying to do, you want to get rid of the last _n_ frame IDs (_n_=sequence length) inside the _frames_ list, in order to not exceed the last available frame when you'll afterwards extract the real 20-steps trajectories from the raw data.

If this is the case, I think the code is not working as expected, since 
https://github.com/zhangpur/SR-LSTM/blob/22de027ff1eb6183fa8c2c60940e2cbf74b46822/utils.py#L157
does not eliminate the last _n_ IDs but only the last 2, because the IDs in _frames_ are separated by a step of 10 (0, 10, 20, 30, ...) and not by a step of 1 (0, 1, 2, 3, ...) as expected. 

If it's not the case, I didn't fully understand those lines.

Thanks in advance for your time :)
Alex

**Comment by cunjunyu** [comment]
I think the issue you pointed out does exist. This might be an error.

However, it may not affect the result a lot since here:
https://github.com/zhangpur/SR-LSTM/blob/22de027ff1eb6183fa8c2c60940e2cbf74b46822/utils.py#L197

The author used a try;except to make it work.

**Comment by alexmonti19** [comment]
> I think the issue you pointed out does exist. This might be an error.
> 
> However, it may not affect the result a lot since here:
> https://github.com/zhangpur/SR-LSTM/blob/22de027ff1eb6183fa8c2c60940e2cbf74b46822/utils.py#L197
> 
> The author used a try;except to make it work.

Yes, I noticed the same lines while further inspecting/debugging the code. They indeed solve the situation however I think it could be useful to patch the problem in the first place and get rid of them :) 

I don't know if the author is still maintaining the repo and/or will read this, anyway I'll leave it here as a future reference in the case someone comes across the same problem.
