### ISSUE TITLE
Rotate shift

### ISSUE THREAD

**Issue by MazenHamdi** [zhangpur/SR-LSTM#7]
Hello, great work there.
I don't really understand what does the shift rotate function do to the batchs, why did you use it and why did you use the batch, batch_norm (batch - shift value) and the shift value ?
Thanks a lot

**Comment by zhangpur** [comment]
Hi,

'shift value' is the last observed position, we substract all absolute coordinates with this offset to make the last value of lstm input as 0. This does not make differences on the predicted error.  You can refer to the original paper for that preprocessings.
